name: WakaTime Readme Stats

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
